### ISSUE TITLE
Mapper for DataOne data packages to usable file names in WholeTale

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/girder_ythub#1]

**Comment by amoeba** [comment]
I wrote up a short script here to show how this can be done:

https://gist.github.com/amoeba/d1071a05aacd20468623eecefdac8f01

It's probably fast enough but it could be sped up by at least 2x if not more. Two notes:

- Each Object in DataONE has a `fileName` attribute (optional). My code doesn't specifically handle the case where the `fileName` is left out. A good fallback would be the PID (sanitized for the file system)
- I generally tried to raise an `Exception` so as to stop the process instead of continuing with possibly inaccurate information but this script should handle the most common cases. I'd be happy to make the code more robust at a later date.

**Comment by Xarthisius** [comment]
I'm going to resolve this issue as the first prototype is working and already deployed. We can refine it the future, but that's going to be separate issue
